name: Build and Deploy .NET Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.x" 

      - name: Restore dependencies
        run: dotnet restore  
        working-directory: .

      - name: Build
        run: dotnet build --configuration Release --no-restore 

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: func-rhym-test
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          working-directory: .
